### ISSUE TITLE
Comments and suggestions

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#12]
+ Write you ID.
+ Give comments about the course.
+ Suggest ideas to make the course better.

**Comment by Antara000** [comment]
- 21181161
- The course is fun and challenging, I really like this lesson because it teaches me a lot. Even though the material is hard, I feel good about figuring it out step by step. This lesson has made me understand about web development better, and I'm excited to keep learning and getting better at it. 
- Studying theory and immediately putting it into practice is very effective. Overcoming challenges to achieve learning goals is helpful for developing thinking and logic in facing obstacles in this course. One area that could be improved is the pace of the learning process; if it feels dull, incorporating games or other interesting activities might help students regain focus.

**Comment by yunisangadji** [comment]
21181298

This lesson is certainly very helpful in creating websites where at first you don't know, so he teaches you how to create websites easily and quickly

f
for this lesson I hope to be able to create a website that can be read by many people and most importantly can be useful for anyone who reads it.

**Comment by robinhuud15** [comment]
21181234

This lesson is very fun because we can learn new things that we didn't know before, the way of teaching applied is very easy to understand so that it makes us enthusiastic about learning

My suggestion is to add variety to the material so that we are more enthusiastic in learning new lessons

**Comment by AKS4R4** [comment]
21181235
the courses feels like a achievements everytime i get it done, and it is quiet complex if you don't pay attention to the tutorials.

these course is perfect as it can be, and i think no further recommendations is needed.

**Comment by irhwam** [comment]
21181125

This courses was challenging as it is quite complex for beginners. If you miss one step in the tutorial, you'll be lost for the rest of the course

This course is already useful and helpful enough

**Comment by Kodhil** [comment]
21181092
This scrapping was really fun, because I gained new knowledge such as SERP and scrapping
My suggestion, hopefully in the future this course can be even better and more new knowledge can be shared with me
